### ISSUE TITLE
Why not using floats on the naviagtion?

### ISSUE THREAD

**Issue by ahmadalfy** [Menna-Elgohary/UI-Assignment-Shopping-cart#6]
https://github.com/Menna-Elgohary/UI-Assignment-Shopping-cart/blob/master/styles/styles.css#L12-L22

**Comment by Menna-Elgohary** [comment]
I thought that it's ok if i do it by inline block or float, So would you please tell me why using float is better or what is the difference them?

**Comment by ahmadalfy** [comment]
We need to move the component that contains the search and login links to the right edge. Right now you are using `margin` with negative value. That doesn't work so well because of the main navigation links increased that will make you change the negative value you use for the margin.

Do you get what I mean?

**Comment by Menna-Elgohary** [comment]
Yes, i got it.
