### ISSUE TITLE
The display of the product card

### ISSUE THREAD

**Issue by ahmadalfy** [Menna-Elgohary/UI-Assignment-Shopping-cart#9]
@Menna-Elgohary 

The display is corrupted the way it is because link that should contain the image (the box in the screenshot below) has its display property set to `inline` by default. You are trying to increase its height using the `padding` property.

You need to change this

```
.item a {
    width: 220px;
    height: 60px;
    background-color: white;
    border: solid;
    border-width: 0.5px;
    border-color: grey;
    padding: 110px 90px;
}

```

Set the `display` property to be `inline-block` and remove the padding. Also set an appropriate `height`. 60px is too small.   Set the `margin` property of the link to be `0 auto` to bring it to the center (cause it's a block remember)?

Let me know. I was going to make a fork and fix the code but I want you to do it :)
![image](https://cloud.githubusercontent.com/assets/87611/13373124/1c79c974-dd67-11e5-9389-66bbe2524040.png)

**Comment by Menna-Elgohary** [comment]
Ok i will try it now ..Thank you :)

**Comment by Menna-Elgohary** [comment]
It is fixed :D

**Comment by ahmadalfy** [comment]
Awesome. I hope you understand why it works when we did it that way. Pay attention to the elements native `display` value. It's the key to understand why these behaviors happen. I never encountered that behavior cause I never set vertical padding on an inline element.

**Comment by Menna-Elgohary** [comment]
Yes i did.
